<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SpineViewerWPF</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SpineViewerWPF.Application/SpineViewerWPF.Application.csproj" />
    <ProjectReference Include="../../runtimes/SpineRuntime.V40/SpineRuntime.V40.csproj" />
    <ProjectReference Include="../../runtimes/SpineRuntime.V41/SpineRuntime.V41.csproj" />
  </ItemGroup>
</Project>
