<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework><ImplicitUsings>disable</ImplicitUsings><Nullable>disable</Nullable><EnableDefaultCompileItems>false</EnableDefaultCompileItems><DefineConstants>$(DefineConstants);SPINE_LEGACY;SPINE_RUNTIME_32XX;SPINE_LEGACY_SHORT;SPINE_LEGACY_OLD_MESH;SPINE_LEGACY_NO_BOUNDS;SPINE_LEGACY_LOWER_BLEND;SPINE_LEGACY_NO_CLIPPING</DefineConstants></PropertyGroup>
  <ItemGroup>
    <Compile Include="../../SpineViewerWPF/SpineLibrary/spine-runtimes-3.2.xx/*.cs" /><Compile Include="../../SpineViewerWPF/SpineLibrary/spine-runtimes-3.2.xx/Attachments/*.cs" />
    <Compile Include="../../SpineViewerWPF/SpineLibrary/spine-runtimes-3.2.xx/Collections/*.cs" />
    <Compile Include="../SpineRuntime.Legacy/Adapter.cs" Link="Adapter.cs" /><Compile Include="../SpineRuntime.V41/CpuRenderer.cs" Link="CpuRenderer.cs" /><Compile Include="../SpineRuntime.V41/PngReader.cs" Link="PngReader.cs" /><Compile Include="../SpineRuntime.V41/PngWriter.cs" Link="PngWriter.cs" />
    <ProjectReference Include="../../src/SpineViewerWPF.Application/SpineViewerWPF.Application.csproj" />
  </ItemGroup>
</Project>
